# Generated by Django 6.0.2 on 2026-02-15 09:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="WhatsApp number in Twilio format: whatsapp:+XXXXXXXXXXXX",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be in Twilio WhatsApp format: whatsapp:+XXXXXXXXXXXX",
                                regex="^whatsapp:\\+\\d{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("worker", "Worker"), ("hse_officer", "HSE Officer")],
                        default="worker",
                        help_text="User role determines access level and logging behaviour",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "safeguardai_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded safety manual or procedure document",
                        upload_to="documents/safety_manuals/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive documents are excluded from RAG search results",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "safeguardai_document",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["-uploaded_at"], name="safeguardai_uploade_accb6d_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="safeguardai_is_acti_c6b593_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SafetyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        help_text="The safety question or task the worker asked about"
                    ),
                ),
                (
                    "safety_check",
                    models.TextField(
                        help_text="Summary of the safety guidance provided"
                    ),
                ),
                (
                    "sources",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list of documents used to generate the answer",
                        max_length=500,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_logs",
                        to="safety.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Log",
                "verbose_name_plural": "Safety Logs",
                "db_table": "safeguardai_safetylog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="safeguardai_timesta_a8b0d3_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Original message from the worker"),
                ),
                (
                    "response",
                    models.TextField(
                        help_text="AI-generated response sent back to the worker"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "Text"), ("voice", "Voice")],
                        default="text",
                        help_text="Whether the worker sent a text or voice message",
                        max_length=10,
                    ),
                ),
                (
                    "response_included_image",
                    models.BooleanField(
                        default=False,
                        help_text="True if the AI response included a generated image (e.g. DALL·E)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="safety.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "safeguardai_conversation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="safeguardai_created_2ec582_idx"
                    )
                ],
            },
        ),
    ]
